---
title: "Causal_Project"
author: "Devin Khosla and Jui Nerurkar"
date: "11/4/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(grf)
library(bcf)
library(arm)
library(mvtnorm)
```

```{r}
#Set seed, determine the number of observations and variables.
set.seed(123)
n <- 10000
p <- 6
```


```{r, warning = F, show = F, message = F}
#Create strongly confounded data - variables: Weight, Age, Tumor Size and Blood Pressure
sigma_mat <- matrix(0, 4,4)
sigma_mat[lower.tri(sigma_mat)] <- c(0.7, 0.8, 0.9, 0.9,0.92, 0.84)
sigma_mat <- t(sigma_mat)
sigma_mat[lower.tri(sigma_mat)] <- c(0.7, 0.8, 0.9, 0.9,0.92, 0.84)
Sigma <- t(sigma_mat) %*% sigma_mat
Sigma <- Sigma/1.5
diag(Sigma) <- c(20, 10, 2, 25)

Xi <- rmvnorm(n, c(170, 50, 5, 130), sigma= Sigma)

#Create data for variables: Gender and Relapse
Gender <- rbinom(n, 1, 0.52)
#Dependent on Tumor size
Relapse <- rbinom(n,1,((Xi[,3]-min(Xi[,3]))/(max(Xi[,3])-min(Xi[,3]))))
```


```{r}
#Add a first column with 1s for the intercept (beta0)
X_mat <- cbind(rep(1,n), Xi, Gender, Relapse)

#Add column names
colnames(X_mat) = c('beta0','Weight','Age','Size_Tumor','HBP', 'Gender','Relapse')

# Parameters 
# beta - vector of slopes to generate Y
beta <- c(-0.98, 0.803,0.17, 0.77, 0.027, 1.18, 0.187)
# vector of slopes to generate tau
gamma <- c(16, -0.060, 0.0124, -1.523, 0.1,  0.64, 0.8)

#Generate tau
tau <- (X_mat)%*%gamma
```

```{r}
X_mat <- data.frame(X_mat)
#Treatment assignment was not completely random. Targeted selection.
q = ifelse(X_mat$Age > 40 & X_mat$Weight < 160 & X_mat$Size_Tumor < 4 & X_mat$Relapse == 0, -1, 1)
pi = pnorm(q)
treat = rbinom(n, 1, pi)
```

```{r}
#Linear data generation process 
#Generate potential outcomes - Y0 and Y1 
Y0_lin <- (as.matrix(X_mat))%*%beta + rnorm(n,0,1)
Y1_lin <- (as.matrix(X_mat))%*%beta + tau + rnorm(n, 0, 1)
```

```{r}
#Non linear data generation process
Y0_nl <- 50 + (sin(X_mat$Weight^(1/3)) + (X_mat$Age^6) + exp(X_mat$Size_Tumor) + X_mat$Relapse) *(10^-9) + rbeta(n,0.5,1/3)

Y1_nl <- 50 + (sin(X_mat$Weight^(1/3)) + (X_mat$Age^6) + exp(X_mat$Size_Tumor) + X_mat$Relapse) *(10^-9) + rbeta(n,0.5,1/3)+ tau
```

```{r}
#Plot tau
hist(tau)
mean(tau)
#The mean value of treatment effect is 12.54
```


```{r}
#Create researcher data and god role data for the linear data
researcher_lin  <- data.frame(X_mat[,-1], treat = treat, Y = ifelse(treat == 1, Y1_lin, Y0_lin))
god_lin <- data.frame(X_mat[,-1], treat = treat, Y1 = Y1_lin, Y0 = Y0_lin, tau = tau)

#Create researcher data and god role data for the non linear data
researcher_nl <- data.frame(X_mat[,-1], treat = treat, Y = ifelse(treat == 1, Y1_nl, Y0_nl))
god_nl <- data.frame(X_mat[,-1], treat = treat, Y1 = Y1_nl, Y0 = Y0_nl, tau = tau)
```

```{r}
#Create train - test split for linear researcher data
rows_lin <- sample(nrow(researcher_lin),size = 0.8*n,replace = F)
train_lin <- researcher_lin[rows_lin,]
test_lin <- god_lin[-rows_lin,]

#Create train - test split for non linear researcher data
rows_nl <- sample(nrow(researcher_nl),size = 0.8*n,replace = F)
train_nl <- researcher_nl[rows_nl,]
test_nl <- god_nl[-rows_nl,]
```

```{r}
# Linear Regression with linear data - train/test approach
fit_lin <- lm(Y ~ Gender + Age + Weight + Size_Tumor + HBP + Relapse + treat,data = train_lin)
summary(fit_lin)
Yhat_lin_lr <- predict.lm(fit_lin, test_lin, type = "response")
plot(fit_lin$fitted.values, fit_lin$residuals, xlab = "", ylab = "")
abline(h = 0, col="red")
title(main = "Diagnostic plot of residuals", xlab = "Fitted values", ylab = "Residuals")
```

```{r}

# Linear Regression with non linear data- train/test approach
fit_nl <- lm(Y ~ Gender + Age + Weight +  Size_Tumor + HBP + Relapse + treat,data = train_nl)
summary(fit_nl)
Yhat_nl_lr <- predict.lm(fit_nl, test_nl, type = "response")
plot(fit_nl$fitted.values, fit_nl$residuals, xlab = "", ylab = "")
abline(h = 0, col="red")
title(main = "Diagnostic plot of residuals", xlab = "Fitted values", ylab = "Residuals")
```

```{r}
#Causal forest with linear data
fit_cf_lin <- causal_forest(X = train_lin[,1:6],Y = train_lin$Y, W = train_lin$treat)
cf.pred_lin <- predict(fit_cf_lin, test_lin[,1:6])

#Predictions on test data
hist(cf.pred_lin$predictions)
mean(cf.pred_lin$predictions)
```

```{r}
#Causal forest with non linear data
fit_cf_nl <- causal_forest(X = train_nl[,1:6],Y = train_nl$Y, W = train_nl$treat)
cf.pred_nl <- predict(fit_cf_nl, test_nl[,1:6])

#Predictions using test data
hist(cf.pred_nl$predictions)
mean(cf.pred_nl$predictions)
```

```{r, show = F, message = F, warning = F, cache = T}
# Bayesian Causal Forest with linear data
fit_bayesian_lin <- bcf(researcher_lin$Y, researcher_lin$treat, as.matrix(researcher_lin[,1:6]),as.matrix(researcher_lin[,1:6]), pihat = pi, nburn = 2000, nsim = 2000)

# Get posterior of treatment effects with linear data
tau_post_lin = fit_bayesian_lin$tau
tauhat_lin = colMeans(tau_post_lin)
hist(tauhat_lin)
mean(tauhat_lin)

#Obtain fitted values
yhat_lin_bcf = colMeans(fit_bayesian_lin$yhat)
```

```{r, show = F, warning = F, message = F, cache = T}
# Bayesian Causal Forest with non linear data
fit_bayesian_nl <- bcf(researcher_nl$Y, researcher_nl$treat, as.matrix(researcher_nl[,1:6]),as.matrix(researcher_nl[,1:6]), pihat = pi, nburn = 2000, nsim = 2000)

# Get posterior of treatment effects with non linear data
tau_post_nl = fit_bayesian_nl$tau
tauhat_nl = colMeans(tau_post_nl)
hist(tauhat_nl)
mean(tauhat_nl)

#Obtain fitted values
yhat_nl_bcf = colMeans(fit_bayesian_nl$yhat)
```


DIAGNOSTICS:

RMSE:
```{r}
#Mean difference in real and estimated individual heterogeneous treatment effects for linear data
mean_diff_lin_bcf = sqrt(mean((tauhat_lin - tau)^2))
print(mean_diff_lin_bcf)
mean_diff_lin_cf = sqrt(mean((cf.pred_lin$predictions - test_lin$tau)^2))
print(mean_diff_lin_cf)

#Mean difference in real and estimated individual heterogeneous treatment effects for non - linear data
mean_diff_nl_bcf = sqrt(mean((tauhat_nl - tau)^2))
print(mean_diff_nl_bcf)
mean_diff_nl_cf = sqrt(mean((cf.pred_nl$predictions - test_nl$tau)^2))
print(mean_diff_nl_cf)
```

```{r}
plot(density(tau - tauhat_lin), main = "")
title(main = "Density - Residuals for BCF using linear data")
plot(density(test_lin$tau - cf.pred_lin$predictions), main = "")
title(main = "Density - Residuals for CF using linear data")
```

```{r}
plot(density(tau - tauhat_nl), main = "")
title(main = "Density - Residuals for BCF using nonlinear data")
plot(density(test_lin$tau - cf.pred_lin$predictions), main = "")
title(main = "Density - Residuals for CF using nonlinear data")
```

OVERLAPPING HISTOGRAMS FOR ACTUAL VALUES OF tau AND PREDICTED tau VALUES USING BCF
```{r}
#Overlapping histograms of tau and estimated tau using BCF - linear data
hist(tauhat_lin, col = rgb(1,0,0, alpha = 0.7), ylim = c(0, 2000), main = "Overlapping Histogram - tau and predicted tau - BCF- Linear data", xlab = "tau/predicted tau")
hist(tau, col = rgb(0,0,1, alpha = 0.7), add = T)

#Overlapping histograms of tau and estimated tau using BCF - non linear data
hist(tauhat_nl, col = rgb(1,0,0, alpha = 0.7), ylim = c(0, 2000), xlim = c(5, 25), main = "Overlapping Histogram - tau and predicted tau - BCF- Nonlinear data", xlab = "tau/predicted tau")
hist(tau, col = rgb(0,0,1, alpha = 0.7), add = T)
```






