---
title: "Causal_Project"
author: "Nerurkar Jui A"
date: "10/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"

data = read.csv(url, header = FALSE)

head(data)

colnames(data) <- c("age", 
"sex" ,
"cp",
"trestbps" ,
"chol" ,
"fbs" ,
"restecg", 
"thalach" ,
"exang", 
"oldpeak", 
"slope",
"ca", 
"thal", "hd") 

str(data)
```

```{r}
data[data == "?"] <- NA

data[data$sex == 0,]$sex = "F"
data[data$sex == 1,]$sex = "M"
data$sex = as.factor(data$sex)

data$cp <- as.factor(data$cp)
data$fbs <- as.factor(data$fbs)
data$restecg <- as.factor(data$restecg)
data$exang <- as.factor(data$exang)
data$slope <- as.factor(data$slope)

data$ca <- as.integer(data$ca)
data$ca <- as.factor(data$ca)

data$thal <- as.integer(data$thal)
data$thal <- as.factor(data$thal)
```

Convert the response variable into binary 0/1 using ifelse()
```{r}
data$hd <- ifelse(data$hd == 0, "Healthy", "Unhealthy")
data$hd <- as.factor(data$hd)
```

Impute missing data
First argument to rfImpute is hd~. which means that the hd column to be predicted by the data in all of the other columns
```{r}
set.seed(42)

data.imputed <- rfImpute(hd ~ ., data = data, iter = 6)
```

